-- Turbo Pascal 7.0 IDE colors: the 16-colour EGA palette, yellow code on a
-- blue desktop, grey Turbo Vision menus/dialogs with red hotkeys and green
-- selection. Syntax colours follow TP7's default Options > Environment >
-- Colors > Editor settings.
vim.cmd("highlight clear")
if vim.g.syntax_on then
  vim.cmd("syntax reset")
end
vim.o.background = "dark"
vim.g.colors_name = "turbopascal"

local c = {
  black = "#000000",
  blue = "#0000AA",
  green = "#00AA00",
  cyan = "#00AAAA",
  red = "#AA0000",
  magenta = "#AA00AA",
  brown = "#AA5500",
  lightgray = "#AAAAAA",
  darkgray = "#555555",
  lightblue = "#5555FF",
  lightgreen = "#55FF55",
  lightcyan = "#55FFFF",
  lightred = "#FF5555",
  lightmagenta = "#FF55FF",
  yellow = "#FFFF55",
  white = "#FFFFFF",
}

-- terminal colours in the same palette, so :terminal/lazygit match
for i, col in ipairs({
  c.black, c.red, c.green, c.brown, c.blue, c.magenta, c.cyan, c.lightgray,
  c.darkgray, c.lightred, c.lightgreen, c.yellow, c.lightblue, c.lightmagenta, c.lightcyan, c.white,
}) do
  vim.g["terminal_color_" .. (i - 1)] = col
end

local groups = {
  -- editor window: yellow text on blue
  Normal = { fg = c.yellow, bg = c.blue },
  NormalNC = { link = "Normal" },
  EndOfBuffer = { fg = c.blue, bg = c.blue },
  NonText = { fg = c.lightblue },
  Whitespace = { fg = c.lightblue },
  SpecialKey = { fg = c.lightblue },
  Conceal = { fg = c.lightgray },
  LineNr = { fg = c.cyan, bg = c.blue },
  LineNrAbove = { link = "LineNr" },
  LineNrBelow = { link = "LineNr" },
  CursorLineNr = { fg = c.white, bg = c.blue, bold = true },
  CursorLine = { bg = c.darkgray },
  CursorColumn = { link = "CursorLine" },
  ColorColumn = { bg = c.darkgray },
  SignColumn = { bg = c.blue },
  FoldColumn = { fg = c.cyan, bg = c.blue },
  Folded = { fg = c.lightcyan, bg = c.blue, italic = true },
  Cursor = { fg = c.blue, bg = c.yellow },
  MatchParen = { fg = c.black, bg = c.cyan, bold = true },

  -- marked block / search
  Visual = { fg = c.blue, bg = c.cyan },
  VisualNOS = { link = "Visual" },
  Search = { fg = c.blue, bg = c.cyan },
  CurSearch = { fg = c.white, bg = c.green, bold = true },
  IncSearch = { link = "CurSearch" },
  Substitute = { link = "CurSearch" },

  -- window frames: white double lines on the active window, grey otherwise
  WinSeparator = { fg = c.white, bg = c.blue },
  VertSplit = { link = "WinSeparator" },
  WinBar = { fg = c.white, bg = c.blue, bold = true },
  WinBarNC = { fg = c.lightgray, bg = c.blue },
  TurboFrameIcon = { fg = c.lightgreen, bg = c.blue },

  -- Turbo Vision menu bar, drop-downs and hint line
  TabLine = { fg = c.black, bg = c.lightgray },
  TabLineFill = { link = "TabLine" },
  TabLineSel = { link = "TabLine" },
  TurboMenu = { fg = c.black, bg = c.lightgray },
  TurboMenuKey = { fg = c.red, bg = c.lightgray },
  TurboMenuSel = { fg = c.black, bg = c.green },
  TurboMenuSelKey = { fg = c.red, bg = c.green },
  TurboShadow = { fg = c.darkgray, bg = c.black },
  StatusLine = { fg = c.black, bg = c.lightgray },
  StatusLineNC = { link = "StatusLine" },
  TurboStatusKey = { fg = c.red, bg = c.lightgray },

  -- dialogs (About, pickers, inputs): black on grey, green focus
  TurboDialog = { fg = c.black, bg = c.lightgray },
  TurboDialogFrame = { fg = c.white, bg = c.lightgray },
  TurboDialogTitle = { fg = c.white, bg = c.lightgray, bold = true },
  TurboButton = { fg = c.white, bg = c.green, bold = true },
  TurboButtonShadow = { fg = c.black, bg = c.lightgray },

  -- status messages (LSP progress, notifications, noice): opaque grey
  -- boxes with their own text colours, so they never read as source code
  TurboStatusMsg = { fg = c.black, bg = c.lightgray },
  TurboStatusMsgTitle = { fg = c.blue, bg = c.lightgray, bold = true },
  TurboStatusMsgDim = { fg = c.darkgray, bg = c.lightgray },
  TurboStatusMsgIcon = { fg = c.red, bg = c.lightgray },
  TurboStatusMsgWarn = { fg = c.magenta, bg = c.lightgray, bold = true },
  TurboStatusMsgError = { fg = c.white, bg = c.red },
  TurboStatusMsgErrorTitle = { fg = c.yellow, bg = c.red, bold = true },

  -- floats that show code (hover, previews) are editor windows: blue
  NormalFloat = { fg = c.yellow, bg = c.blue },
  FloatBorder = { fg = c.white, bg = c.blue },
  FloatTitle = { fg = c.white, bg = c.blue, bold = true },
  Pmenu = { fg = c.black, bg = c.lightgray },
  PmenuSel = { fg = c.black, bg = c.green },
  PmenuKind = { fg = c.blue, bg = c.lightgray },
  PmenuKindSel = { fg = c.blue, bg = c.green },
  PmenuExtra = { fg = c.darkgray, bg = c.lightgray },
  PmenuExtraSel = { fg = c.black, bg = c.green },
  PmenuSbar = { bg = c.cyan },
  PmenuThumb = { bg = c.blue },
  WildMenu = { link = "PmenuSel" },
  QuickFixLine = { fg = c.black, bg = c.cyan },

  -- messages
  ModeMsg = { fg = c.white, bold = true },
  MsgArea = { fg = c.yellow, bg = c.blue },
  MoreMsg = { fg = c.lightgreen },
  Question = { fg = c.lightgreen },
  ErrorMsg = { fg = c.white, bg = c.red, bold = true },
  WarningMsg = { fg = c.lightmagenta },
  Title = { fg = c.white, bold = true },
  Directory = { fg = c.white, bold = true },

  -- syntax (TP7 defaults)
  Comment = { fg = c.lightgray },
  Keyword = { fg = c.white },
  Statement = { fg = c.white },
  Conditional = { fg = c.white },
  Repeat = { fg = c.white },
  Label = { fg = c.white },
  Exception = { fg = c.white },
  StorageClass = { fg = c.white },
  Structure = { fg = c.white },
  Typedef = { fg = c.white },
  PreProc = { fg = c.lightgreen },
  Include = { fg = c.white },
  Define = { fg = c.lightgreen },
  Macro = { fg = c.lightgreen },
  PreCondit = { fg = c.lightgreen },
  Identifier = { fg = c.yellow },
  Function = { fg = c.yellow },
  Type = { fg = c.yellow },
  Operator = { fg = c.yellow },
  Delimiter = { fg = c.yellow },
  String = { fg = c.lightcyan },
  Character = { fg = c.lightcyan },
  Number = { fg = c.lightcyan },
  Float = { fg = c.lightcyan },
  Boolean = { fg = c.lightcyan },
  Constant = { fg = c.lightcyan },
  Special = { fg = c.lightgreen },
  SpecialChar = { fg = c.lightgreen },
  Tag = { fg = c.white },
  Underlined = { fg = c.lightcyan, underline = true },
  Todo = { fg = c.black, bg = c.yellow, bold = true },
  Error = { fg = c.white, bg = c.red },

  ["@variable"] = { fg = c.yellow },
  ["@variable.builtin"] = { fg = c.white },
  ["@variable.parameter"] = { fg = c.yellow },
  ["@variable.member"] = { fg = c.yellow },
  ["@property"] = { fg = c.yellow },
  ["@constant.builtin"] = { fg = c.lightcyan },
  ["@module"] = { fg = c.yellow },
  ["@type.builtin"] = { fg = c.white },
  ["@function.builtin"] = { fg = c.yellow },
  ["@constructor"] = { fg = c.yellow },
  ["@keyword"] = { fg = c.white },
  ["@keyword.directive"] = { fg = c.lightgreen },
  ["@string.escape"] = { fg = c.lightgreen },
  ["@string.special"] = { fg = c.lightgreen },
  ["@punctuation"] = { fg = c.yellow },
  ["@comment"] = { link = "Comment" },
  ["@comment.todo"] = { link = "Todo" },
  ["@comment.error"] = { fg = c.white, bg = c.red },
  ["@comment.warning"] = { fg = c.black, bg = c.brown },
  ["@comment.note"] = { fg = c.black, bg = c.cyan },
  ["@tag"] = { fg = c.white },
  ["@tag.attribute"] = { fg = c.yellow },
  ["@tag.delimiter"] = { fg = c.yellow },
  ["@markup.heading"] = { fg = c.white, bold = true },
  ["@markup.strong"] = { fg = c.white, bold = true },
  ["@markup.italic"] = { italic = true },
  ["@markup.link"] = { fg = c.lightcyan, underline = true },
  ["@markup.raw"] = { fg = c.lightcyan },
  ["@markup.list"] = { fg = c.white },
  ["@diff.plus"] = { fg = c.lightgreen },
  ["@diff.minus"] = { fg = c.lightred },
  ["@diff.delta"] = { fg = c.lightcyan },

  -- diagnostics / diffs / git
  DiagnosticError = { fg = c.lightred },
  DiagnosticWarn = { fg = c.lightmagenta },
  DiagnosticInfo = { fg = c.lightcyan },
  DiagnosticHint = { fg = c.lightgreen },
  DiagnosticOk = { fg = c.lightgreen },
  DiagnosticUnderlineError = { undercurl = true, sp = c.lightred },
  DiagnosticUnderlineWarn = { undercurl = true, sp = c.lightmagenta },
  DiagnosticUnderlineInfo = { undercurl = true, sp = c.lightcyan },
  DiagnosticUnderlineHint = { undercurl = true, sp = c.lightgreen },
  DiagnosticUnnecessary = { fg = c.lightgray },
  LspInlayHint = { fg = c.cyan, italic = true },
  LspCodeLens = { fg = c.cyan },
  LspReferenceText = { bg = c.darkgray },
  LspReferenceRead = { bg = c.darkgray },
  LspReferenceWrite = { bg = c.darkgray },
  DiffAdd = { fg = c.white, bg = c.green },
  DiffDelete = { fg = c.white, bg = c.red },
  DiffChange = { fg = c.black, bg = c.cyan },
  DiffText = { fg = c.white, bg = c.magenta, bold = true },
  Added = { fg = c.lightgreen },
  Removed = { fg = c.lightred },
  Changed = { fg = c.lightcyan },
  GitSignsAdd = { fg = c.lightgreen, bg = c.blue },
  GitSignsChange = { fg = c.lightcyan, bg = c.blue },
  GitSignsDelete = { fg = c.lightred, bg = c.blue },
  SpellBad = { undercurl = true, sp = c.lightred },
  SpellCap = { undercurl = true, sp = c.lightcyan },

  -- plugins: pickers and prompts are Turbo Vision dialogs
  TelescopeNormal = { link = "TurboDialog" },
  TelescopeBorder = { link = "TurboDialogFrame" },
  TelescopeTitle = { link = "TurboDialogTitle" },
  TelescopePromptNormal = { fg = c.white, bg = c.blue },
  TelescopePromptBorder = { link = "TurboDialogFrame" },
  TelescopePromptPrefix = { fg = c.lightgreen, bg = c.blue },
  TelescopePromptCounter = { fg = c.lightgray, bg = c.blue },
  TelescopeSelection = { link = "TurboMenuSel" },
  TelescopeSelectionCaret = { link = "TurboMenuSel" },
  TelescopeMatching = { fg = c.red, bold = true },
  TelescopePreviewNormal = { link = "Normal" },
  TelescopePreviewBorder = { link = "FloatBorder" },
  TelescopePreviewTitle = { link = "FloatTitle" },
  WhichKey = { fg = c.red, bg = c.lightgray },
  WhichKeyNormal = { link = "TurboDialog" },
  WhichKeyBorder = { link = "TurboDialogFrame" },
  WhichKeyTitle = { link = "TurboDialogTitle" },
  WhichKeyDesc = { fg = c.black },
  WhichKeyGroup = { fg = c.blue },
  WhichKeySeparator = { fg = c.darkgray },
  NoiceCmdlinePopup = { link = "TurboDialog" },
  NoiceCmdlinePopupBorder = { link = "TurboDialogFrame" },
  NoiceCmdlinePopupTitle = { link = "TurboDialogTitle" },
  NoiceCmdlineIcon = { fg = c.blue, bg = c.lightgray },
  SnacksInputNormal = { link = "TurboDialog" },
  SnacksInputBorder = { link = "TurboDialogFrame" },
  SnacksInputTitle = { link = "TurboDialogTitle" },
  -- Snacks pickers (the explorer, Options > Compiler): TP windows, yellow on
  -- blue with a white double frame, TP input line and a cyan selection bar
  SnacksPickerInput = { fg = c.white, bg = c.blue },
  SnacksPickerInputBorder = { fg = c.cyan, bg = c.blue },
  SnacksPickerPrompt = { fg = c.white, bg = c.blue, bold = true },
  SnacksPickerList = { fg = c.yellow, bg = c.blue },
  SnacksPickerListCursorLine = { fg = c.black, bg = c.cyan },
  SnacksPickerMatch = { fg = c.lightred, bold = true },
  SnacksPickerBox = { link = "SnacksPickerList" },
  SnacksPickerBoxBorder = { link = "WinSeparator" },
  SnacksPickerBoxTitle = { link = "WinBar" },
  SnacksPickerTree = { fg = c.cyan },
  SnacksPickerDirectory = { fg = c.white, bold = true },
  SnacksPickerPathHidden = { fg = c.lightgray },
  SnacksPickerPathIgnored = { fg = c.cyan },
  SnacksPickerGitStatusUntracked = { fg = c.lightgray },
  SnacksPickerGitStatusIgnored = { fg = c.cyan },
  SnacksPickerTotals = { fg = c.lightgray },
  SnacksDashboardNormal = { link = "Normal" },
  SnacksDashboardHeader = { fg = c.yellow, bold = true },
  SnacksDashboardFooter = { fg = c.lightgray },
  SnacksDashboardKey = { fg = c.red, bg = c.lightgray },
  SnacksDashboardDesc = { fg = c.white },
  SnacksDashboardIcon = { fg = c.lightcyan },
  SnacksIndent = { fg = c.lightblue },
  SnacksNotifierInfo = { link = "TurboStatusMsg" },
  SnacksNotifierBorderInfo = { link = "TurboDialogFrame" },
  SnacksNotifierTitleInfo = { link = "TurboStatusMsgTitle" },
  SnacksNotifierIconInfo = { link = "TurboStatusMsgTitle" },
  SnacksNotifierFooterInfo = { link = "TurboDialogFrame" },
  SnacksNotifierWarn = { link = "TurboStatusMsg" },
  SnacksNotifierBorderWarn = { link = "TurboStatusMsgWarn" },
  SnacksNotifierTitleWarn = { link = "TurboStatusMsgWarn" },
  SnacksNotifierIconWarn = { link = "TurboStatusMsgWarn" },
  SnacksNotifierFooterWarn = { link = "TurboStatusMsgWarn" },
  SnacksNotifierError = { link = "TurboStatusMsgError" },
  SnacksNotifierBorderError = { link = "TurboStatusMsgErrorTitle" },
  SnacksNotifierTitleError = { link = "TurboStatusMsgErrorTitle" },
  SnacksNotifierIconError = { link = "TurboStatusMsgErrorTitle" },
  SnacksNotifierFooterError = { link = "TurboStatusMsgErrorTitle" },
  SnacksNotifierDebug = { link = "TurboStatusMsgDim" },
  SnacksNotifierBorderDebug = { link = "TurboDialogFrame" },
  SnacksNotifierTitleDebug = { link = "TurboStatusMsgDim" },
  SnacksNotifierIconDebug = { link = "TurboStatusMsgDim" },
  SnacksNotifierFooterDebug = { link = "TurboDialogFrame" },
  SnacksNotifierTrace = { link = "TurboStatusMsgDim" },
  SnacksNotifierBorderTrace = { link = "TurboDialogFrame" },
  SnacksNotifierTitleTrace = { link = "TurboStatusMsgDim" },
  SnacksNotifierIconTrace = { link = "TurboStatusMsgDim" },
  SnacksNotifierFooterTrace = { link = "TurboDialogFrame" },
  NoiceMini = { link = "TurboStatusMsg" },
  BlinkCmpMenu = { link = "Pmenu" },
  BlinkCmpMenuBorder = { fg = c.white, bg = c.lightgray },
  BlinkCmpMenuSelection = { link = "PmenuSel" },
  BlinkCmpDoc = { link = "NormalFloat" },
  BlinkCmpDocBorder = { link = "FloatBorder" },
  BlinkCmpLabelMatch = { fg = c.red, bold = true },
  MinuetVirtualText = { fg = c.lightgray, italic = true },
  LightBulbSign = { bg = c.blue },
  DapUIVariable = { fg = c.yellow },
  DapUIScope = { fg = c.white, bold = true },
  DapUIType = { fg = c.lightcyan },
  DapUIDecoration = { fg = c.white },
  DapUIThread = { fg = c.lightgreen },
  DapUIStoppedThread = { fg = c.lightgreen, bold = true },
  DapUIFrameName = { fg = c.yellow },
  DapUISource = { fg = c.lightcyan },
  DapUILineNumber = { fg = c.cyan },
  DapUIFloatBorder = { link = "FloatBorder" },
  DapUIWatchesEmpty = { fg = c.lightred },
  DapUIWatchesValue = { fg = c.lightgreen },
  DapUIWatchesError = { fg = c.lightred },
  DapUIBreakpointsPath = { fg = c.white },
  DapUIBreakpointsInfo = { fg = c.lightgreen },
  DapUIBreakpointsCurrentLine = { fg = c.lightgreen, bold = true },
  -- TP marks the execution point with a cyan bar, breakpoints with red
  DapStoppedLine = { fg = c.black, bg = c.cyan },
  DapBreakpointLine = { fg = c.white, bg = c.red },
}

for name, spec in pairs(groups) do
  vim.api.nvim_set_hl(0, name, spec)
end
