[Service]
Environment="OLLAMA_IGPU_ENABLE=1"
Environment="OLLAMA_VULKAN=true"
Environment="OLLAMA_CONTEXT_LENGTH=8192"
Environment="OLLAMA_FLASH_ATTENTION=1"
Environment="OLLAMA_KEEP_ALIVE=10m"
Environment="OLLAMA_MAX_LOADED_MODELS=1"
MemoryHigh=10G
