local state    = require("turbovim.state")
local keymaps  = require("turbovim.keymaps")
local dropdown = require("turbovim.dropdown")
local bar      = require("turbovim.bar")

local function get_cb(key)
  local info = vim.fn.maparg(key, "n", false, true)
  return info and info.callback
end

local function reset_state()
  state.active         = false
  state.item_idx       = 1
  state.dropdown_open  = false
  state.dropdown_idx   = 1
  state.dropdown_buf   = nil
  state.dropdown_win   = nil
  state.dropdown_items = nil
  state.dropdown_lines = nil
  state.dropdown_menu  = nil
end

-- generated by ollama (gemma4)
local alt_keys = {
  { key = "<M-f>", idx = 1, label = "File" },
  { key = "<M-e>", idx = 2, label = "Edit" },
  { key = "<M-s>", idx = 3, label = "Search" },
  { key = "<M-c>", idx = 4, label = "Code" },
  { key = "<M-d>", idx = 5, label = "Database" },
  { key = "<M-r>", idx = 6, label = "Run" },
  { key = "<M-a>", idx = 7, label = "AI" },
  { key = "<M-w>", idx = 8, label = "Window" },
  { key = "<M-h>", idx = 9, label = "Help" },
}

-- ── F10 toggle ──────────────────────────────────────────────────────────────

describe("keymaps: F10 toggle", function()
  before_each(reset_state)
  after_each(function() keymaps.deactivate() end)

  it("F10 activates the menu bar", function()
    local cb = get_cb("<F10>")
    assert.is_not_nil(cb, "<F10> keymap not registered")
    cb()
    assert.is_true(state.active)
  end)

  it("F10 deactivates when already active", function()
    local cb = get_cb("<F10>")
    cb()
    cb()
    assert.is_false(state.active)
  end)
end)

-- ── Alt-letter shortcuts ─────────────────────────────────────────────────────

describe("keymaps: Alt-letter shortcuts", function()
  local orig_open

  before_each(function()
    reset_state()
    orig_open     = dropdown.open
    dropdown.open = function() state.dropdown_open = true end
  end)

  after_each(function()
    dropdown.open = orig_open
    keymaps.deactivate()
  end)

  for _, t in ipairs(alt_keys) do
    it(t.key .. " opens " .. t.label .. " menu at idx " .. t.idx, function()
      local cb = get_cb(t.key)
      assert.is_not_nil(cb, t.key .. " keymap not registered")
      cb()
      assert.equals(t.idx, state.item_idx)
      assert.is_true(state.dropdown_open)
    end)
  end
end)

-- ── Navigation (activated keymaps) ──────────────────────────────────────────

describe("keymaps: navigation", function()
  local orig_open, orig_close, orig_refresh

  before_each(function()
    reset_state()
    orig_open     = dropdown.open
    orig_close    = dropdown.close
    orig_refresh  = bar.refresh
    -- stub rendering so tests don't need floating windows or a screen
    dropdown.open  = function() state.dropdown_open = true end
    dropdown.close = function()
      state.dropdown_open  = false
      state.dropdown_items = nil
    end
    bar.refresh = function() end
    keymaps.activate()
  end)

  after_each(function()
    dropdown.open  = orig_open
    dropdown.close = orig_close
    bar.refresh    = orig_refresh
    keymaps.deactivate()
  end)

  it("<Right> advances to the next menu", function()
    state.item_idx = 1
    get_cb("<Right>")()
    assert.equals(2, state.item_idx)
  end)

  it("<Right> wraps from last menu to first", function()
    state.item_idx = 9
    get_cb("<Right>")()
    assert.equals(1, state.item_idx)
  end)

  it("<Left> retreats to the previous menu", function()
    state.item_idx = 3
    get_cb("<Left>")()
    assert.equals(2, state.item_idx)
  end)

  it("<Left> wraps from first menu to last", function()
    state.item_idx = 1
    get_cb("<Left>")()
    assert.equals(9, state.item_idx)
  end)

  it("<CR> opens the dropdown when it is closed", function()
    state.dropdown_open = false
    get_cb("<CR>")()
    assert.is_true(state.dropdown_open)
  end)

  it("<Down> opens the dropdown when it is closed", function()
    state.dropdown_open = false
    get_cb("<Down>")()
    assert.is_true(state.dropdown_open)
  end)

  it("<Right> with open dropdown closes and reopens on the new menu", function()
    state.dropdown_open = true
    state.item_idx = 1
    get_cb("<Right>")()
    assert.equals(2, state.item_idx)
    assert.is_true(state.dropdown_open)
  end)

  it("<Left> with open dropdown closes and reopens on the new menu", function()
    state.dropdown_open = true
    state.item_idx = 3
    get_cb("<Left>")()
    assert.equals(2, state.item_idx)
    assert.is_true(state.dropdown_open)
  end)

  it("<Esc> closes the dropdown without deactivating", function()
    state.dropdown_open = true
    get_cb("<Esc>")()
    assert.is_false(state.dropdown_open)
    assert.is_true(state.active)
  end)

  it("<Esc> deactivates when dropdown is already closed", function()
    state.dropdown_open = false
    get_cb("<Esc>")()
    assert.is_false(state.active)
  end)
end)
