#!/usr/bin/env bash
# install-ollama-macos.sh — Apply the RAM-matched Ollama env profile on macOS.
#
# macOS has no systemd, so the systemd drop-ins in ollama/ollama.service.d/
# don't apply here. The Ollama.app menubar server picks up variables set with
# `launchctl setenv`, so this script reads ollama/launchd/<profile>.env and
# exports each key that way, then restarts the app so it re-reads them.
#
# `launchctl setenv` does not survive a reboot, so the same values are also
# written to ~/.ollama/dotfiles.env and sourced from ~/.zshrc — that covers
# `ollama serve` started by hand from a shell. Re-run after a reboot (or just
# `make install-ollama`) to re-apply them to the menubar app.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

PROFILE="$("$SCRIPT_DIR/detect-ram-profile.sh")"
ENV_FILE="$REPO_DIR/ollama/launchd/$PROFILE.env"

if [ ! -f "$ENV_FILE" ]; then
	echo "  ✗ no macOS Ollama profile at $ENV_FILE" >&2
	exit 1
fi

echo "  → RAM profile: $PROFILE (from $ENV_FILE)"

if ! command -v ollama >/dev/null 2>&1 && [ ! -d /Applications/Ollama.app ]; then
	echo "  ⚠ Ollama not found — skipping (brew install --cask ollama)"
	exit 0
fi

# Apply to the running launchd session (what Ollama.app inherits).
while IFS= read -r line; do
	case "$line" in ''|\#*) continue ;; esac
	key="${line%%=*}"
	val="${line#*=}"
	launchctl setenv "$key" "$val"
	echo "     $key=$val"
done < "$ENV_FILE"

# Persist for shell-launched `ollama serve` across reboots.
mkdir -p "$HOME/.ollama"
{
	echo "# Generated by scripts/install-ollama-macos.sh — do not edit."
	echo "# Source profile: ollama/launchd/$PROFILE.env"
	while IFS= read -r line; do
		case "$line" in ''|\#*) continue ;; esac
		echo "export $line"
	done < "$ENV_FILE"
} > "$HOME/.ollama/dotfiles.env"
echo "  ✓ wrote ~/.ollama/dotfiles.env (sourced by ~/.zshrc)"

# Restart Ollama.app so the server re-reads the launchd environment.
if pgrep -x Ollama >/dev/null 2>&1; then
	echo "  ↻ restarting Ollama.app to pick up the new environment..."
	osascript -e 'quit app "Ollama"' >/dev/null 2>&1 || pkill -x Ollama || true
	sleep 2
fi
if [ -d /Applications/Ollama.app ]; then
	open -a Ollama
	echo "  ✓ Ollama.app running with the $PROFILE profile"
else
	echo "  ⚠ Ollama.app not installed — env applied for CLI 'ollama serve' only"
fi
