#!/usr/bin/env bash
# setup-host.sh — Tune the local LLM stack (LM Studio + pi + zsh env) to this
# machine's hardware. One GPU-detection pass picks a profile, then it:
#   • LM Studio — downloads/keeps the right Qwen2.5-Coder-7B quant for the VRAM.
#   • mu        — writes the KV-cache context (MU_NUM_CTX) the card can hold to
#                 ~/.zshrc.local (machine-local, outside the repo). Only mu reads it.
#   • pi        — sets defaultModel in ~/.pi/agent/settings.json (the 7B on a
#                 capable card, the snappier 3B otherwise).
#
# ~/.zshrc and ~/.pi/agent/* are symlinks into this repo, shared by every host
# (an 8 GB M2, a 6 GB GTX, and a 32 GB Intel Meteor Lake iGPU today). The
# committed configs stay host-agnostic:
# the per-host context lives in the untracked ~/.zshrc.local (sourced by .zshrc
# before its defaults), and pi's defaultModel is host-managed — each machine's
# run sets its own, so that one field shouldn't be committed with a host's value.
#
# Idempotent: re-run after a GPU change and it rewrites the profile (and removes
# ~/.zshrc.local when the host falls back to the conservative default context).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ZSHRC_LOCAL="$HOME/.zshrc.local"

# ── Detect GPU VRAM (NVIDIA only; Macs use unified memory, handled as default) ─
nvidia_vram_mib() {
    command -v nvidia-smi > /dev/null 2>&1 || return 1
    nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2>/dev/null \
      | head -n1 | tr -dc '0-9'
}
nvidia_name() {
    nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -n1
}

VRAM_MIB=""
GPU_DESC="none detected (using unified-memory / conservative default)"
if [ "$(uname -s)" = "Linux" ]; then
    VRAM_MIB="$(nvidia_vram_mib || true)"
    [ -n "${VRAM_MIB:-}" ] && GPU_DESC="$(nvidia_name) — ${VRAM_MIB} MiB VRAM"
fi

# ── Pick a hardware profile ───────────────────────────────────────────────────
# A discrete NVIDIA card with ≥6 GB has room for the larger Q4_K_M weights plus a
# bigger KV cache (measured: 7B Q4_K_M at 12288 ctx loads fully on a 6 GB card,
# ~5.3/6.0 GB used). Everything else — the Mac, Intel iGPU machines, smaller/older
# cards — stays on the Q3_K_L/6000 defaults that the committed configs already encode.
if [ -n "${VRAM_MIB:-}" ] && [ "$VRAM_MIB" -ge 6000 ] 2>/dev/null; then
    PROFILE="roomy"
    QUANT="Q4_K_M"
    NUM_CTX="12288"
    PI_DEFAULT_MODEL="qwen2.5-coder-7b-instruct"   # capable card → pi defaults to the 7B
else
    PROFILE="default"
    QUANT="Q3_K_L"
    NUM_CTX="6000"                                 # the committed MU_NUM_CTX default
    PI_DEFAULT_MODEL="qwen2.5-coder-3b-instruct"   # conservative → snappier 3B default
fi

echo "Host hardware profile"
echo "  GPU:        $GPU_DESC"
echo "  Profile:    $PROFILE"
echo "  LM Studio:  Qwen2.5-Coder-7B $QUANT"
echo "  MU_NUM_CTX: $NUM_CTX"
echo "  pi model:   $PI_DEFAULT_MODEL"
echo ""

# ── 1. LM Studio: download/keep the right quant ───────────────────────────────
# Hand the chosen quant down so setup-lmstudio.sh skips its own GPU probe.
echo "── LM Studio ───────────────────────────────────────────────"
QUANT="$QUANT" bash "$SCRIPT_DIR/setup-lmstudio.sh"
echo ""

# ── 2. mu: per-host KV-cache context via ~/.zshrc.local ───────────────────────
# Only mu reads MU_NUM_CTX (it passes it on the LM Studio load). The committed
# .zshrc already defaults it to 6000, so the override file is only needed when a
# roomier card raises it; on the default profile we remove it so the host falls
# back cleanly. This is the machine-local file, outside the repo — never tracked.
echo "── mu context (~/.zshrc.local) ─────────────────────────────"
if [ "$NUM_CTX" = "6000" ]; then
    if [ -e "$ZSHRC_LOCAL" ]; then
        rm -f "$ZSHRC_LOCAL"
        echo "  ✓ Removed $ZSHRC_LOCAL — MU_NUM_CTX uses the committed default (6000)"
    else
        echo "  ✓ No override needed; MU_NUM_CTX uses the committed default (6000)"
    fi
else
    {
        echo "# ~/.zshrc.local — generated by scripts/setup-host.sh. Do not edit;"
        echo "# re-run 'make setup-host' to regenerate. Machine-local, outside the repo."
        echo "# Host: $(uname -n) | GPU: $GPU_DESC | profile: $PROFILE"
        echo ""
        echo "export MU_NUM_CTX=$NUM_CTX"
    } > "$ZSHRC_LOCAL"
    echo "  ✓ Wrote $ZSHRC_LOCAL (MU_NUM_CTX=$NUM_CTX)"
fi
echo ""

# ── 3. pi: set the default model in the agent settings ────────────────────────
# pi reads ~/.pi/agent/settings.json (a symlink into this repo). Patch only the
# hardware-derived field, defaultModel, leaving the rest untouched. Because the
# file is shared across machines, this field is host-managed: each host's
# 'make setup-host' sets its own value, so don't commit a host-specific default.
echo "── pi agent (~/.pi/agent/settings.json) ────────────────────"
PI_SETTINGS="$HOME/.pi/agent/settings.json"
if [ -f "$PI_SETTINGS" ]; then
    python3 - "$PI_SETTINGS" "$PI_DEFAULT_MODEL" <<'PYEOF'
import json, sys
path, model = sys.argv[1], sys.argv[2]
with open(path) as f:
    s = json.load(f)
if s.get("defaultModel") == model:
    print(f"  ✓ defaultModel already '{model}'")
else:
    old = s.get("defaultModel", "<unset>")
    s["defaultModel"] = model
    with open(path, "w") as f:
        json.dump(s, f, indent=2)
        f.write("\n")
    print(f"  ✓ defaultModel: {old} → {model}")
PYEOF
else
    echo "  ⚠ $PI_SETTINGS not found — run 'make install-pi' first, then re-run."
fi
echo ""

echo "Host setup complete. Open a new shell (or 'source ~/.zshrc') to apply."
